swagger: "2.0"
info:
  title: "Job Server API"
  version: "1.0.0"
  description: "채용정보 서버 API 문서"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /api/auth/register:
    post:
      tags:
        - "인증"
      summary: "회원가입"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: "회원가입 성공"
  /api/auth/login:
    post:
      tags:
        - "인증"
      summary: "로그인"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: "로그인 성공"
