openapi: 3.0.0
info:
  title: OurJobs API
  description: 채용정보 검색 및 지원 API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /jobs:
    get:
      summary: 채용공고 목록 조회
      parameters:
        - in: query
          name: location
          schema:
            type: string
          description: 지역 필터
        - in: query
          name: page
          schema:
            type: integer
          description: 페이지 번호
      responses:
        '200':
          description: 채용공고 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
  /apply/{job_id}:
    post:
      summary: 채용공고 지원
      parameters:
        - in: path
          name: job_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 지원 성공
components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        company:
          type: string
        location:
          type: string
